# nixpacks.toml

[phases.setup]
# We need both Node.js (for npm) and Bun (for the start command).
nixPkgs = ["nodejs", "bun"]

[phases.install]
# THIS IS THE FIX:
# Force the build server to use the same command that worked locally.
cmd = "npm install --force"

[start]
# Tell Dokploy how to run your app after it's built.
cmd = "bun run start"