[phases.setup]
# Setup phase for preparing the environment
nixPkgs = ["bun", "nodejs"]

[phases.install]
# Install phase for dependencies
cmd = ["bun install"]

[phases.build]
# Build phase for building the application
cmd = ["bun run build"]

[start]
# Start phase for running the application
cmd = "bun run start"
